# SVM for classification

In [12]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [13]:
df = pd.read_csv('./titanic-processed.csv')

In [14]:
df.head()

Survived   Age     Fare  TravelAlone  Pclass_1  Pclass_2  Pclass_3  \
0         0  22.0   7.2500            0         0         0         1   
1         1  38.0  71.2833            0         1         0         0   
2         1  26.0   7.9250            1         0         0         1   
3         1  35.0  53.1000            0         1         0         0   
4         0  35.0   8.0500            1         0         0         1   

   Embarked_C  Embarked_Q  Embarked_S  Sex_male  IsMinor  
0           0           0           1         1        0  
1           1           0           0         0        0  
2           0           0           1         0        0  
3           0           0           1         0        0  
4           0           0           1         1        0

# SCALING THE FEATURES BECUASE SVM WORKS ON DISTANCE BASED MATHEMATICS

In [15]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df2 = df.drop('Survived',axis=1)
model=scaler.fit(df2)
scaled_data=model.transform(df2)

In [16]:
scaled_data

array([[0.27117366, 0.01415106, 0.        , ..., 1.        , 1.        ,
        0.        ],
       [0.4722292 , 0.13913574, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.32143755, 0.01546857, 1.        , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.34656949, 0.04577135, 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.32143755, 0.0585561 , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.39683338, 0.01512699, 1.        , ..., 0.        , 1.        ,
        0.        ]])

In [17]:
X = scaled_data
y = df['Survived']

In [18]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X,y,random_state=50,test_size=0.3) 

# SVM MODEL IMPLEMENTATION

In [19]:
from sklearn import svm
from sklearn.metrics import accuracy_score

In [20]:
clf = svm.SVC(kernel='rbf') # rbf works best for this model
clf.fit(train_X,train_y)

SVC()

 The 'kernel' parameter of SVC must be a str among {'precomputed', 'linear', 'poly', 'sigmoid', 'rbf'} or a callable.

In [21]:
y_ = clf.predict(test_X)
y__ = clf.predict(train_X)

In [23]:
train_accuracy =  accuracy_score(y__,train_y)
test_accuracy = accuracy_score(y_,test_y)
print(f'training accuracy = {train_accuracy}')
print(f'testing accuracy = {test_accuracy}')

training accuracy = 0.8314606741573034
testing accuracy = 0.8171641791044776


# Metrics evaluation 

In [24]:
from sklearn.metrics import confusion_matrix, f1_score

In [26]:
confusion_matrix(test_y,y_)

array([[157,   5],
       [ 44,  62]])

In [27]:
confusion_matrix(train_y,y__)

array([[370,  17],
       [ 88, 148]])

In [29]:
print(f'F1 score for the test set : {f1_score(test_y,y_)}')

F1 score for the test set : 0.7167630057803467
